"""Criar tabela de usuários

Revision ID: a26815710032
Revises: 
Create Date: 2024-09-28 16:58:48.730080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a26815710032'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
        sa.Column('ID_usuario', sa.Integer(), nullable=False),
        sa.Column('nome', sa.String(length=100), nullable=False),
        sa.Column('usuario', sa.String(length=50), nullable=False),
        sa.Column('senha_hash', sa.String(length=128), nullable=False),
        sa.PrimaryKeyConstraint('ID_usuario'),
        sa.UniqueConstraint('usuario')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuario')  # Corrigido para 'usuario'
    # ### end Alembic commands ###
